// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB_z07aLmmuUZjN3asXBdinwtQ8VT6ZF9w',
    appId: '1:812800543659:web:0d8411209a1e7de5c520ee',
    messagingSenderId: '812800543659',
    projectId: 'e-commerce-app-1cab7',
    authDomain: 'e-commerce-app-1cab7.firebaseapp.com',
    storageBucket: 'e-commerce-app-1cab7.firebasestorage.app',
    measurementId: 'G-QFHM63CKNK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAHn2chDzA4hHJo6f7bk2xmUtdo1L_lEB0',
    appId: '1:812800543659:android:4b65e91f5ce57befc520ee',
    messagingSenderId: '812800543659',
    projectId: 'e-commerce-app-1cab7',
    storageBucket: 'e-commerce-app-1cab7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC87Ak8f7LjfjQP6K1PERt5Z7lWTPx1qts',
    appId: '1:812800543659:ios:3b8de757dc8b8eedc520ee',
    messagingSenderId: '812800543659',
    projectId: 'e-commerce-app-1cab7',
    storageBucket: 'e-commerce-app-1cab7.firebasestorage.app',
    iosBundleId: 'com.example.eCommerce',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC87Ak8f7LjfjQP6K1PERt5Z7lWTPx1qts',
    appId: '1:812800543659:ios:3b8de757dc8b8eedc520ee',
    messagingSenderId: '812800543659',
    projectId: 'e-commerce-app-1cab7',
    storageBucket: 'e-commerce-app-1cab7.firebasestorage.app',
    iosBundleId: 'com.example.eCommerce',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB_z07aLmmuUZjN3asXBdinwtQ8VT6ZF9w',
    appId: '1:812800543659:web:fd80daa24a6ff21ec520ee',
    messagingSenderId: '812800543659',
    projectId: 'e-commerce-app-1cab7',
    authDomain: 'e-commerce-app-1cab7.firebaseapp.com',
    storageBucket: 'e-commerce-app-1cab7.firebasestorage.app',
    measurementId: 'G-0MX4MLRLR7',
  );
}
